from selenium.webdriver.common.by import By

class HomePageLocatorsLinks:
    BATTON_NACHATb_BESPLATNO = (By.XPATH, '//*[@id="header"]/nav/a')
    BATTON_POPROBOVATb = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[1]/div[2]/div[1]/div/a')
    BATTON_POPROBOVATb_BESPLATNO = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[1]/div[2]/a')
    BATTON_VISUALISIROVATb_STRUCTURU = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[2]/div[2]/div[1]/div/a')
    BATTON_SOZDATb_IZ_SHABLONA = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/a')
    BATTON_SOZDATb_S_NOLJA = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[4]/div/div[2]/a')
    BATTON_GOD_MESJAC = (By.XPATH, '//*[@id="tariffs"]/div/div/div[1]/div[1]/div/div/div/span[2]')
    BATTON_NACHATb_PROBNII = (By.XPATH, '//*[@id="tariffs"]/div/div/div[2]/div[1]/div[1]/div/div/a')
    BATTON_PODCLUCHITb_FREELANCER = (By.XPATH, '//*[@id="tariffs"]/div/div/div[2]/div[2]/div[1]/div[2]/div/a')
    BATTON_PODCLUCHITb_COMANDA = (By.XPATH, '//*[@id="tariffs"]/div/div/div[2]/div[3]/div[1]/div[2]/div/a')
    BATTON_PODCLUCHITb_COMPANIA = (By.XPATH, '//*[@id="tariffs"]/div/div/div[2]/div[4]/div[1]/div[2]/div/a')

    LINK_HOW_WORK_KRAULER_1 = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[2]/li/a')
    LINK_TARIFI_1 = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[3]/li/a')
    LINK_BLOG_HEADER = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[4]/li/a')
    LINK_ONAS_VCRU = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[2]/div[2]/div[2]/a[1]')
    LINK_ONAS_TG = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[2]/div[2]/div[2]/a[2]')
    LINK_ONAS_VK = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[2]/div[2]/div[2]/a[3]')
    LINK_ONAS_BLOG = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[2]/div[2]/div[2]/span/a')
    LINK_SITEMAPS_1 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[2]/div[3]/div[1]/div[2]/a[1]')
    LINK_STRUCTURAaPP_1 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[2]/div[3]/div[1]/div[2]/a[2]')
    LINK_OSNOVAT_STRUCTURA = (By.XPATH, '//*[@id="experts"]/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/p/a')
    LINK_HOW_WORK_KRAULER_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[2]/div[3]/div[2]/a')
    LINK_BLANK_AGENT = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[1]')
    LINK_BLANK_FRILANC = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[2]')
    LINK_BLANK_CORPORAT = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[3]')
    LINK_BLANK_PROMOsITE = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[4]')
    LINK_BLANK_INTERNETsTOR = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[5]')
    LINK_BLANK_OTHER = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[3]/div/div[2]/div/a[6]')
    LINK_GO_TO_BLOG = (By.XPATH, '//*[@id="blog"]/div[1]/div[2]/a')
    LINK_TG_GROUP = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[1]')
    LINK_YOUTUBE_GROUP = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[2]')
    LINK_VK_GROUP = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[3]')
    LINK_NIZ_TARIFI = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[1]/li/a')
    LINK_NIZ_HOW_WORK_KRAULER = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[2]/li/a')
    LINK_NIZ_BLOG = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[3]/li/a')
    LINK_NIZ_CASE = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[4]/li/a')
    LINK_CONFIDENC = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[3]/a[1]')
    LINK_POLZOVAT_SOGLAS = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[3]/a[2]')
    LINK_PRINCIP_RABOTI_KRAULERA = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[2]/li/a')
    LINK_HOW_WORK_KRAULER_HEAD = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[2]/li/a')

    LINK_VIDEO_WORK = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[2]/div/div[1]/div[1]')
    LINK_VIDEO_SlISTA = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/section[3]/div/div/div[4]/div/div[1]')

    IT_IS_VIDEO = (By.XPATH, '//*[@id="movie_player"]/a')
    LINK_VIDEO_CLOSE = (By.XPATH, '/html/body/div/div/div[2]/div/div[3]')
