from selenium.webdriver.common.by import By
class HowWorkKrauPageLocators:
    BATTON_NACHATb_BESPLATNO = (By.XPATH, '//*[@id="header"]/nav/a')
    BATTON_VISUALISIROVATb_STRUCTURU = (By.XPATH, '//*[@id="__next"]/div/div[2]/div[2]/div/div[1]/div[1]/div/a')
    LINK_HOME_PAGE = (By.XPATH, '//*[@id="header"]/nav/div[2]/div[2]/span')
    LINK_SITEMAPS_1 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div[1]/div/div[2]/div[5]/div[2]/div/a[1]')
    LINK_STRUCTURA_APP_1 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div[1]/div/div[2]/div[5]/div[2]/div/a[2]')
    LINK_SITEMAPS_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div[2]/div/div[3]/a[1]')
    LINK_STRUCTURA_APP_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/div[2]/div/div[3]/a[2]')
    LINK_TARIFI_1 = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[3]/li/a')
    LINK_HOW_WORK_KRAULER_HEADER = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[2]/li/a')
    LINK_BLOG_HEADER = (By.XPATH, '//*[@id="header"]/nav/menu/ul/div[4]/li/a')
    LINK_CASE_1 = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[4]/li/a')
    LINK_POLITIKA_KOFIDENC = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[3]/a[1]')
    LINK_USER_OFERTA = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[3]/a[2]')
    LINK_HOW_WORK_KRAULER_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[2]/li/a')
    LINK_TARIFI_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[1]/li/a')
    LINK_BLOG_2 = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[2]/div[1]/ul/div[3]/li/a')
    LINK_TELEGRAMM = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[1]')
    LINK_YOUTUBE = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[2]')
    LINK_VK = (By.XPATH, '//*[@id="__next"]/div/div[2]/section/div/div[1]/div[3]/a[3]')

